# Generated by Django 5.0 on 2024-01-12 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_about_work'),
    ]

    operations = [
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='work',
            name='date_end',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='date_start',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='month',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blogapp.month'),
            preserve_default=False,
        ),
    ]
